
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dac pacific LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const backgroundImageStyle = {
  //   backgroundImage:
  //     "url('https://www.apparelentrepreneurship.com/wp-content/uploads/2023/01/How-To-Make-Your-Clothing-Brand-Stand-Out-In-A-Competitive-Market.jpg')",

  //   backgroundBlendMode: "",
  //   backgroundSize: "cover",
  //   backgroundRepeat: "repeat",
  //   backgroundPosition: "center",
  // };
  const tailwindCss = "w-full";
  const classes = inter.className;
  const combinedClassName = `${tailwindCss} ${classes}`;
  return (
    <html lang="en">
      <body className={combinedClassName}>
        {children}
      </body>
    </html>
  );
}
