import Navbar from "@/Components/shared/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/Components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dac pacific",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const backgroundImageStyle = {
  //   backgroundImage:
  //     "url('https://www.apparelentrepreneurship.com/wp-content/uploads/2023/01/How-To-Make-Your-Clothing-Brand-Stand-Out-In-A-Competitive-Market.jpg')",

  //   backgroundBlendMode: "",
  //   backgroundSize: "cover",
  //   backgroundRepeat: "repeat",
  //   backgroundPosition: "center",
  // };

  return (
    <html lang="en">
      <body >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
